/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 .\\earth.glb 
Author: JohnXina6And9 (https://sketchfab.com/JohnXina6And9)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-8b5123335cc94de29b9d698b78432bd4
Title: Earth
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/earth.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="52fef2676c9748aea61bc7ae2605e1fefbx" rotation={[Math.PI / 2, 0, 0]} scale={0.03}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Sphere002" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Sphere002_Material001_0" geometry={nodes.Sphere002_Material001_0.geometry} material={materials['Material.001']} />
                </group>
                <group name="Sphere003" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Sphere003_Material002_0" geometry={nodes.Sphere003_Material002_0.geometry} material={materials['Material.002']} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/earth.glb')
