/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 .\\glass_bottle.glb 
Author: gelmi.com.br (https://sketchfab.com/rodrigogelmi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/beer-bottle-c3de7f8b092e4092aef14d4ffc9fac7f
Title: Beer Bottle
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/glass_bottle.glb')
  return (
    <group {...props} dispose={null} scale={0.13} position={[0,-3,0]}>
      <mesh geometry={nodes.GARRAFA_VIDRO_FORA_0.geometry} material={materials.VIDRO_FORA} />
      <mesh geometry={nodes.GARRAFA_VIDRO_DENTRO_0.geometry} material={materials.VIDRO_DENTRO} />
      <mesh geometry={nodes.GARRAFA_LIQUIDO_0.geometry} material={materials.LIQUIDO} />
      <mesh geometry={nodes.GARRAFA_TAMPA_0.geometry} material={materials.TAMPA} />
      <mesh geometry={nodes.GARRAFA_LIMITE_LIQUIDO_0.geometry} material={materials.LIMITE_LIQUIDO} />
    </group>
  )
}

useGLTF.preload('/glass_bottle.glb')
