/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 hospital_bin.glb 
Author: teeart (https://sketchfab.com/teeart)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hospital-bin-ccdbba1a590545d3a561cf0f7cdbd9a9
Title: Hospital Bin
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/hospital_bin.glb')
  return (
    <group {...props} dispose={null} scale={0.03} position={[0,-2,0]}>
      <mesh geometry={nodes['Box001_Material_#3_0'].geometry} material={materials.Material_3} position={[5.415, 0, -5.878]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 0.718, 1]} />
      <mesh geometry={nodes['Line001_Material_#4_0'].geometry} material={materials.Material_4} position={[8.821, 0, 30.279]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/hospital_bin.glb')
