/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 .\\ld_shoe_men_2.glb 
Author: sara3dbear (https://sketchfab.com/sara3dbear)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ld-shoe-men-2-517d1fd2e0dc49bf8fe786643433055b
Title: Ld Shoe Men 2
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/ld_shoe_men_2.glb')
  return (
    <group {...props} dispose={null} scale={0.025}>
      <mesh geometry={nodes.Object_8.geometry} material={materials.Material_26} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/ld_shoe_men_2.glb')
