/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 .\\metal_sheet.glb 
Author: Islide (https://sketchfab.com/Islide)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/metal-sheet-low-poly-realist-0b3e4e7bcbdf4ff1bd556403b6f1b827
Title: Metal Sheet [Low Poly Realist]
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default  function Model(props) {
  const { nodes, materials } = useGLTF('/metal_sheet.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={3}>
        <mesh geometry={nodes.iso_PR_Sheet_iso_PR_Sheet_SHD_0.geometry} material={materials.iso_PR_Sheet_SHD} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/metal_sheet.glb')
